name: Release update
on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: Artifact name
        type: string
        required: true
      tagName:
        description: Tag name
        type: string
        required: true
      prerelease:
        description: Prerelease
        type: boolean
        required: true
      releaseName:
        description: Release name
        type: string
        required: true

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5
      - name: Build release APK
        run: ./gradlew assembleRelease
      - name: Rename artifact
        run: mv build/outputs/apk/**/**/*.apk "${{ github.event.inputs.artifactName }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Release APK
          path: ${{ github.event.inputs.artifactName }}

  publish-github-release:
    runs-on: ubuntu-latest
    needs: build-release-apk
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: Release APK
          path: artifacts/release-apk
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tagName }}
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: true
          files: artifacts/release-apk/${{ github.event.inputs.artifactName }}
          name: ${{ github.event.inputs.releaseName }}